FROM python:3.12-alpine AS builder

WORKDIR /app

COPY requirements-docs.txt mkdocs.yml ./
RUN pip install --no-cache-dir -r requirements-docs.txt

COPY docs ./docs
COPY README.md PALMSCRIPT_REFERENCE.md ./

RUN mkdocs build --strict

FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY docker/docs-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/site /usr/share/nginx/html

EXPOSE 8080
